// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_jFln--8421_1EGyr2YZ0Y0J9gLvETs',
    appId: '1:967485528373:android:fcc9f1a10b3dc8ed2c147c',
    messagingSenderId: '967485528373',
    projectId: 'social-life-3005d',
    storageBucket: 'social-life-3005d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOPofyaX2hKJVBKrHutLHfuk9JVzo4umo',
    appId: '1:967485528373:ios:e30dbbd6c2639e192c147c',
    messagingSenderId: '967485528373',
    projectId: 'social-life-3005d',
    storageBucket: 'social-life-3005d.appspot.com',
    androidClientId: '967485528373-1uk2ck87nc78pndi04hj3lbc43ehs0q4.apps.googleusercontent.com',
    iosClientId: '967485528373-378j08j0dluqjfh5hkcn4p0kb3t2jrjh.apps.googleusercontent.com',
    iosBundleId: 'com.ios.app.sociallife',
  );
}
